### ISSUE TITLE
small error with argument 'by_name'

### ISSUE THREAD

**Issue by fortunto2** [keunwoochoi/music-auto_tagging-keras#10]
Hi, sorry but why?

```
rustam@rustam-ssd2:~/github/music-auto_tagging-keras$ python example_feat_extract.py
Using Theano backend.
Running main() with network: crnn and backend: theano
Traceback (most recent call last):
  File "example_feat_extract.py", line 64, in <module>
    main(net)
  File "example_feat_extract.py", line 52, in main
    model = MusicTaggerCRNN(weights='msd', include_top=False)
  File "/home/rustam/github/music-auto_tagging-keras/music_tagger_crnn.py", line 140, in MusicTaggerCRNN
    by_name=True)
TypeError: load_weights() got an unexpected keyword argument 'by_name'
```
ubuntu 16
anaconda python 2.7
keras 1.0.7 
theano  0.8.2

**Comment by keunwoochoi** [comment]
by_name option is available in recent Keras. Not sure from which version but 1.1 would definitely work.

**Comment by fortunto2** [comment]
thanks. update to 1.2 get work!
