### ISSUE TITLE
Audioread module

### ISSUE THREAD

**Issue by mv00147** [keunwoochoi/music-auto_tagging-keras#14]
Dear sir/madam,
 When I run example_tagging.py I get the following error
Couldn't import dot_parser, loading of dot files will not be possible.
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
Traceback (most recent call last):
  File "example_tagging.py", line 6, in <module>
    import audio_processor as ap
  File "/user/HS224/mv00147/Desktop/py_env/lib/python2.7/site-packages/audio_processor.py", line 1, in <module>
    import librosa
  File "/user/HS224/mv00147/Desktop/py_env/lib/python2.7/site-packages/librosa/__init__.py", line 15, in <module>
    from . import core
  File "/user/HS224/mv00147/Desktop/py_env/lib/python2.7/site-packages/librosa/core/__init__.py", line 90, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/user/HS224/mv00147/Desktop/py_env/lib/python2.7/site-packages/librosa/core/audio.py", line 9, in <module>
    import audioread
ImportError: No module named audioread
Can anyone help?
Warm regards,
Mahi :)

**Comment by keunwoochoi** [comment]
Hi, seems like there are two issues. Check out if you have a gpu and if its driver is installed, as well as is configured with PATH variable. Audioread is a python library that librosa uses to load audio files. try to install librosa again (`$ pip install librosa --upgrade` or something similar) and if it doesn't work probably you have to install Audioread by yourself.

**Comment by mv00147** [comment]
Dear sir,

 Thank you so much for your immediate response. I installed audio read. Also, since my GPU is still not set up, I plan to run it on the CPU itself. But I get the following error when I try to install h5py module.

Downloading/unpacking h5py
  Downloading h5py-2.7.0rc2.tar.gz (256Kb): 256Kb downloaded
  Running setup.py egg_info for package h5py
    zip_safe flag not set; analyzing archive contents...

    Installed /user/HS224/mv00147/py_env/lib/python2.7/site-packages/build/h5py/pkgconfig-1.2.2-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/user/HS224/mv00147/py_env/lib/python2.7/site-packages/build/h5py/setup.py", line 165, in <module>
        cmdclass = CMDCLASS,
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (numpy 1.6.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('numpy>=1.7'))
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...



Installed /user/HS224/mv00147/py_env/lib/python2.7/site-packages/build/h5py/pkgconfig-1.2.2-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/user/HS224/mv00147/py_env/lib/python2.7/site-packages/build/h5py/setup.py", line 165, in <module>

    cmdclass = CMDCLASS,

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (numpy 1.6.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('numpy>=1.7'))

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /user/HS224/mv00147/.pip/pip.log
 Could you suggest a way forward?
Many thanks,

Mahalakshmi

________________________________

**Comment by keunwoochoi** [comment]
(answered at #15)
