### ISSUE TITLE
No backend error

### ISSUE THREAD

**Issue by DAKSHSEMWAL** [keunwoochoi/music-auto_tagging-keras#35]
while running[example_tagger.py](https://github.com/DAKSHSEMWAL/music-auto_tagging-keras/blob/master/example_tagging.py)I am constantly getiing this error:
Traceback (most recent call last):
  File "I:\Coding\music-auto_tagging-keras-master\example_feat_extract.py", line 431, in <module>
    main(net)
  File "I:\Coding\music-auto_tagging-keras-master\example_feat_extract.py", line 408, in main
    melgram = ap.compute_melgram(audio_path)
  File "I:\Coding\music-auto_tagging-keras-master\audio_processor.py", line 24, in compute_melgram
    src, sr = librosa.load(audio_path, sr=SR)  # whole signal
  File "C:\Python27\lib\site-packages\librosa\core\audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Python27\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
NoBackendError
what should I do about this

-----------------------------------------------
this is my data set
                   ['music/bensound-cute.mp3',
                   'music/bensound-actionable.mp3',
                   'music/bensound-dubstep.mp3',
                   'music/bensound-thejazzpiano.mp3',
                   'music/"24k Magic.mp3"',
                   'music/"7 Years.mp3"',
                   'music/"A-Sky-Full-Of-Stars-Hardwell-Remix.mp3"',
                   'music/"Addicted To You.mp3"',
                   'music/"Alesso-Heroes.mp3"',
                   'music/"All Time Low.mp3"',
                   'music/"Alone Marshmallow.mp3"',
                   'music/Alone.mp3''music/Animals_MartinGarrix.mp3',
                   'music/Arcadia.mp3',
                   'music/"Area 51".mp3',
                   'music/Ariana_Grande-Baby.mp3',
                   'music/"Avicii - Waiting For Love (Marshmello Remix).mp3"',
                   'music/"Avicii - Waiting for Love (Original Mix).mp3"',
                   'music/"Avicii feat Aluna George What Would I Change It To.mp3"',
                   'music/"Avicii feat Billy Raffoul You Be Love.mp3"',
                   'music/"Avicii feat Rita Ora Lonely Together.mp3"',
                   'music/"Avicii feat. Sandro Cavazza Without You.mp3"',
                   'music/"Avicii feat. Vargas and Lagola Friend Of Mine.mp3"',
                   'music/"avicii wake me up.mp3"',
                   'music/"Bad (feat. Vassy) [Radio Edit].mp3"',
                   'music/"Bad (feat. Vassy).mp3"',
                   'music/"Bang my Head (feat. Sia).mp3"',
                   'music/Barcelona.mp3',
                   'music/"Bibia Be Ye Ye.mp3"',
                   'music/"Birds Fly.mp3"',
                   'music/"Blank Space.mp3"',
                   'music/"Boulevard of broken dreams.mp3"',
                   'music/"Broken Arrows.mp3"',
                   'music/"Carry Me (feat. Julia Michaels).mp3"',
                   'music/"Castle On the Hill.mp3"',
                   'music/"City Lights.mp3"',
                   'music/classic-mkto.mp3',
                   'music/"Clean Bandit - Rockabye ft. Sean Paul Lyrics Video NEW 2016.mp3"',
                   'music/Colors.mp3',
                   'music/Dangerous (feat. Sam Martin).mp3"',
                   'music/Daylight.mp3',
                   'music/"Dear Boy.mp3"',
                   'music/"Despacito - Remix.mp3"',
                   'music/Dive.mp3',
                   'music/"DJ Snake - Let Me Love You ft Justin Bieber (Marshmello Remix).mp3"',
                   'music/"don t you worry child.mp3"',
                   'music/Echo.mp3',
                   'music/Eclipse.mp3',
                   'music/"Ed Sheeran - Perfect.mp3"',
                   'music/Edom.mp3',
                   'music/"Enrique Iglesias - Somebody s Me.mp3"',
                   'music/Eraser.mp3',
                   'music/example.mp3',
                   'music/Faded.mp3',
                   'music/"Fiction (feat. Tom Odell).mp3"',
                   'music/"Firestone (feat. Conrad Sewell).mp3"',
                   'music/"Florida whistle.mp3"',
                   'music/"Follow Me.mp3"',
                   'music/"For A Better Day.mp3"',
                   'music/Fragile.mp3',
                   'music/"Galway Girl.mp3"',
                   'music/"Give me love.mp3"',
                   'music/"Gonna Love Ya.mp3"',
                   'music/Good_Enough.mp3',
                   'music/"Goodbye Friend (feat. The Script).mp3"',
                   'music/Happier.mp3',
                   'music/"Happy Birthday (feat. John Legend).mp3"',
                   'music/"Hardwell feat ,Jake Reese-Mad World.MP3"',
                   'music/"Heart Attack .mp3"',
                   'music/"Heart Upon My Sleeve.mp3"'
                   'music/"Hearts Don t Break Around Here.mp3"',
                   'music/"Hello-marshmello-remix.mp3"',
                   'music/"Hey Baby.mp3"',
                   'music/"Hey Brother.mp3"',
                   'music/"Hey Mama (feat. Nicki Minaj & Afrojack).mp3"',
                   'music/Homeless.mp3',
                   'music/"How Deep Is Your Love.mp3"',
                   'music/"How Would You Feel (Paean).mp3"',
                   'music/"I Love It.mp3"',
                   'music/"I Took A Pill In Ibiza.mp3"',
                   'music/I_Bet_My_Life.mp3',
                   'music/"If I Never See Your Face Again.mp3"',
                   'music/"Imagine Dragons - Believer.mp3"',
                   'music/"Imagine Dragons - Walking The Wire (Audio).mp3"',
                   'music/"in the end.mp3"',
                   'music/"Intro.mp3',
                   'music/"Just the Way You Are .mp3"',
                   'music/"Kiss Me.mp3"',
                   'music/"Lay Me Down.mp3"',
                   'music/"Lego house .mp3"',
                   'music/"Let Me Be Your Home.mp3"',
                   'music/"Let Me Be Your Lover (feat. Pitbull).mp3"',
                   'music/"Let Me Love You - DJ Snake Justin Bieber (320kbps)-(MusicVilla.In).mp3"',
                   'music/"Levels.mp3"',
                   'music/"Liar Liar.mp3"',
                   'music/"Lift me up (feat. Nico & Vinz, Ladysmith Black Mambazo).mp3"',
                   'music/Linkin_Park_-_Powerless.mp3',
                   'music/"Listen (feat. John Legend).mp3"',
                   'music/"Long Road To Hell.mp3"',
                   'music/love-story.mp3',
                   'music/"Lovers on the Sun (feat. Sam Martin).mp3"',
                   'music/"Major Lazer - Cold Water.mp3"',
                   'music/"Mark Ronson - Uptown Funk (Ft. Bruno Mars).mp3"',
                   'music/"Maroon 5 - Maps.mp3"',
                   'music/"Maroon 5 Misery.mp3"',
                   'music/"Maroon-5-Love-Somebody.mp3"',
                   'music/"Marshmello Ookay ft. Noah Cyrus - Chasing Colors.mp3"',
                   'music/"Marshmello - Summer.mp3"',
                   'music/"Marshmello_ft_Khalid_-_Silence_Talkmuzik.mp3"',
                   'music/"Marvin Gaye.mp3"',
                   'music/"moves like jagger.mp3"',
                   'music/"Nancy Mulligan.mp3"',
                   'music/"New Man.mp3"',
                   'music/"No Money no Love (feat. Elliphant & Ms. Dynamite).mp3"',
                   'music/"Not Alone (feat. RHODES).mp3"',
                   'music/"Nothing Can Hold Us Down.mp3"',
                   'music/"Nothing Left (feat. Will Heard).mp3"',
                   'music/numb.mp3',
                   'music/"Oasis (feat. Foxes).mp3"',
                   'music/"One last time.mp3"',
                   'music/"Owl City - Fireflies2.mp3"',
                   'music/"Payphone (feat. Wiz Khalifa).mp3"',
                   'music/"payphone alex goot.mp3"',
                   'music/"Photograph.mp3"',
                   'music/"Pure Grinding.mp3"',
                   'music/"Raging (feat. Kodaline).mp3"',
                   'music/"Rap God.mp3"',
                   'music/"Rise (feat. Skylar Grey).mp3"',
                   'music/"S.T.O.P (feat. Ryan Tedder).mp3"',
                   'music/"Sally.mp3"',
                   'music/"Save Myself.mp3"',
                   'music/"See You Again.mp3"',
                   'music/"Selena Gomez - Hands To Myself.mp3"',
                   'music/"Selena Gomez - Kill Em With Kindness.mp3"',
                   'music/"Serious (feat. Matt Corby).mp3"',
                   'music/"Shame On Me.mp3"',
                   'music/"Shape of you.mp3"',
                   'music/"She Will Be Loved.mp3"',
                   'music/"Shot me Down (feat. Skylar Grey) [Radio Edit].mp3"',
                   'music/"Sia - Cheap Thrills (ft. Sean Paul) - 320 Kbps-(MusicVilla.In).mp3"',
                   'music/"Simple Plan - Perfect.mp3"',
                   'music/"Sing Me to Sleep (Marshmello Remix).mp3"',
                   'music/Sing Me to Sleep.mp3"',
                   'music/"Sing.mp3"',
                   'music/"Somewhere In Stockholm.mp3"',
                   'music/"Stand By Me.mp3"',
                   'music/"Stay (feat. Maty Noyes).mp3"',
                   'music/"Stereo Hearts.mp3"',
                   'music/"Stole the Show (feat. Parson James).mp3"',
                   'music/"Sugar.mp3"',
                   'music/"SUMMER OF 69.MP3"',
                   'music/"Sun Goes Down (feat. MAGIC! & Sonny Wilson).mp3"',
                   'music/"Sunset Jesus.mp3"',
                   'music/"Supermarket Flowers.mp3"',
                   'music/"Sweater Weather.mp3"',
                   'music/"Talk To Myself.mp3"',
                   'music/"Ten More Days.mp3"',
                   'music/"The A Team.mp3"',
                   'music/"The Chainsmokers Coldplay - Something Just Like This.mp3"',
                   'music/"The Chainsmokers - All We Know ft. Phoebe Ryan.mp3"',
                   'music/"The Chainsmokers - Roses.mp3"',
                   'music/"The Chainsmokers DJ Snake Ft. Zayn - I Know - 2017.mp3 (Mp3goo.com).mp3"',
                   'music/"The Whisperer (feat. Sia).mp3"',
                   'music/"Thinking Out Loud .mp3"',
                   'music/"Thousands years.mp3"',
                   'music/"Thunder - Imagine Dragons.mp3"',
                   'music/"Titanium Feat Sia.mp3"',
                   'music/"Tonight (I m Lovin You).mp3"',
                   'music/"Touch Me.mp3"',
                   'music/"Trouble.mp3"',
                   'music/"True Believer.mp3"',
                   'music/"United We Are.mp3',
                   'music/"Urban Cone Weekends.mp3"',
                   'music/"Versace On The Floor.mp3"',
                   'music/"Waiting For Love.mp3"',
                   'music/"waiting for love(prinston $ astrid s Acoustic version).MP3"',
                   'music/"Wake Me Up.mp3"',
                   'music/"What Do I Know.mp3"',
                   'music/"What I did for Love.mp3"',
                   'music/"When i was you man.mp3"',
                   'music/"Where Is Here Now.mp3"',
                   'music/"Wont Go Home Without You.mp3"',
                   'music/"Wrecking Ball.mp3"',
                   'music/"Yesterday (feat.Bebe Rexha).mp3"',
                   'music/"You Make Me.mp3"',
                   'music/"Youre Beautiful.mp3"',
                   'music/"Young Again.mp3"',
                   'music/"your song.mp3"']

these are the dependencies that i have installed
appdirs (1.4.3)
audioread (2.1.5)
cycler (0.10.0)
Cython (0.25.2)
decorator (4.2.1)
enum34 (1.1.6)
ffmpy (0.2.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
h5py (2.7.0)
joblib (0.11)
Keras (2.1.3)
librosa (0.5.1)
llvmlite (0.21.0)
matplotlib (2.0.0)
numba (0.36.2)
numpy (1.14.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2017.2)
PyYAML (3.12)
resampy (0.2.0)
scikit-learn (0.19.1)
scipy (1.0.0)
setuptools (38.5.1)
singledispatch (3.4.0.3)
six (1.11.0)
subprocess32 (3.2.7)
Theano (0.9.0)
wheel (0.30.0)

**Comment by DAKSHSEMWAL** [comment]
thanks
